[package]
name = "zero_to_prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero_to_prod"

[dependencies]
axum = "0.6"
tokio = {version="1.23", features=["full"]}
hyper = "0.14"

[dev-dependencies]
reqwest = "0.11"